# Generated by Django 5.2.7 on 2025-10-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=100, unique=True)),
                ('warehouse_location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dra_warehouse',
                'ordering': ['warehouse_name'],
                'indexes': [models.Index(fields=['warehouse_name'], name='dra_warehou_warehou_324df9_idx')],
            },
        ),
    ]
