# Generated by Django 5.2.7 on 2025-10-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyRestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
            options={
                'db_table': 'dra_product',
                'ordering': ['product_name'],
                'indexes': [models.Index(fields=['product_name'], name='dra_product_product_e1ba66_idx')],
            },
        ),
    ]
