# Generated by Django 5.2.7 on 2025-10-30 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyRestApp', '0002_dummyproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dummyRestApp.dummyproduct')),
                ('id_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dummyRestApp.dummywarehouse')),
            ],
            options={
                'db_table': 'dra_inventory',
                'ordering': ['id_warehouse__id', 'id_product__id'],
                'indexes': [models.Index(fields=['id_warehouse', 'id_product'], name='dra_invento_id_ware_527493_idx')],
                'constraints': [models.UniqueConstraint(fields=('id_warehouse', 'id_product'), name='unique_inventory_item')],
            },
        ),
    ]
