# Generated by Django 5.2.7 on 2025-10-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyRestApp', '0003_dummyinventory'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dummyinventory',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='stock_must_be_non_negative'),
        ),
    ]
