# Generated by Django 5.2.7 on 2025-10-30 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyRestApp', '0004_dummyinventory_stock_must_be_non_negative'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='dummyRestApp.dummyproduct')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='dummyRestApp.dummywarehouse')),
            ],
            options={
                'db_table': 'dra_stockmovement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['warehouse', 'product'], name='dra_stockmo_warehou_cd8942_idx'), models.Index(fields=['transaction_type'], name='dra_stockmo_transac_231ab3_idx'), models.Index(fields=['-created_at'], name='dra_stockmo_created_e9dbaa_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quantity_must_be_positive')],
            },
        ),
    ]
